name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ¤– The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository}}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ’» The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "â„¹ï¸ This job's status is ${{ job.status }}."

  Simulating-Deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy_and_integration
    steps:
      - run: echo "â±ï¸simulating deploy on Cluster"
      - name: simulating Time
        uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: '2m'

  Simulating-Integration:
    runs-on: ubuntu-latest
    needs: ["Simulating-Deploy"]
    concurrency:
      group: deploy_and_integration
    steps:
      - run: echo "â±ï¸simulating integrationtests"
      - name: simulating Time
        uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: '5m'
